#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoreBVN
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="BVN_IW")]
	public partial class ApprovalListConnectionDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertIC_A_User(IC_A_User instance);
    partial void UpdateIC_A_User(IC_A_User instance);
    partial void DeleteIC_A_User(IC_A_User instance);
    #endregion
		
		public ApprovalListConnectionDataContext() : 
				base(global::CoreBVN.Properties.Settings.Default.BVN_IWConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public ApprovalListConnectionDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ApprovalListConnectionDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ApprovalListConnectionDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ApprovalListConnectionDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<IC_A_User> IC_A_Users
		{
			get
			{
				return this.GetTable<IC_A_User>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.IC_A_Users")]
	public partial class IC_A_User : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _StaffNumber;
		
		private string _StaffName;
		
		private string _Emails;
		
		private string _Grade;
		
		private string _Branch;
		
		private string _Jobtitle;
		
		private string _DeptTitle;
		
		private System.Nullable<int> _AdminRole;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnStaffNumberChanging(string value);
    partial void OnStaffNumberChanged();
    partial void OnStaffNameChanging(string value);
    partial void OnStaffNameChanged();
    partial void OnEmailsChanging(string value);
    partial void OnEmailsChanged();
    partial void OnGradeChanging(string value);
    partial void OnGradeChanged();
    partial void OnBranchChanging(string value);
    partial void OnBranchChanged();
    partial void OnJobtitleChanging(string value);
    partial void OnJobtitleChanged();
    partial void OnDeptTitleChanging(string value);
    partial void OnDeptTitleChanged();
    partial void OnAdminRoleChanging(System.Nullable<int> value);
    partial void OnAdminRoleChanged();
    #endregion
		
		public IC_A_User()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StaffNumber", DbType="VarChar(150) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string StaffNumber
		{
			get
			{
				return this._StaffNumber;
			}
			set
			{
				if ((this._StaffNumber != value))
				{
					this.OnStaffNumberChanging(value);
					this.SendPropertyChanging();
					this._StaffNumber = value;
					this.SendPropertyChanged("StaffNumber");
					this.OnStaffNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StaffName", DbType="VarChar(150)")]
		public string StaffName
		{
			get
			{
				return this._StaffName;
			}
			set
			{
				if ((this._StaffName != value))
				{
					this.OnStaffNameChanging(value);
					this.SendPropertyChanging();
					this._StaffName = value;
					this.SendPropertyChanged("StaffName");
					this.OnStaffNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Emails", DbType="VarChar(150)")]
		public string Emails
		{
			get
			{
				return this._Emails;
			}
			set
			{
				if ((this._Emails != value))
				{
					this.OnEmailsChanging(value);
					this.SendPropertyChanging();
					this._Emails = value;
					this.SendPropertyChanged("Emails");
					this.OnEmailsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Grade", DbType="VarChar(150)")]
		public string Grade
		{
			get
			{
				return this._Grade;
			}
			set
			{
				if ((this._Grade != value))
				{
					this.OnGradeChanging(value);
					this.SendPropertyChanging();
					this._Grade = value;
					this.SendPropertyChanged("Grade");
					this.OnGradeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Branch", DbType="VarChar(150)")]
		public string Branch
		{
			get
			{
				return this._Branch;
			}
			set
			{
				if ((this._Branch != value))
				{
					this.OnBranchChanging(value);
					this.SendPropertyChanging();
					this._Branch = value;
					this.SendPropertyChanged("Branch");
					this.OnBranchChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Jobtitle", DbType="VarChar(150)")]
		public string Jobtitle
		{
			get
			{
				return this._Jobtitle;
			}
			set
			{
				if ((this._Jobtitle != value))
				{
					this.OnJobtitleChanging(value);
					this.SendPropertyChanging();
					this._Jobtitle = value;
					this.SendPropertyChanged("Jobtitle");
					this.OnJobtitleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DeptTitle", DbType="VarChar(150)")]
		public string DeptTitle
		{
			get
			{
				return this._DeptTitle;
			}
			set
			{
				if ((this._DeptTitle != value))
				{
					this.OnDeptTitleChanging(value);
					this.SendPropertyChanging();
					this._DeptTitle = value;
					this.SendPropertyChanged("DeptTitle");
					this.OnDeptTitleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AdminRole", DbType="Int")]
		public System.Nullable<int> AdminRole
		{
			get
			{
				return this._AdminRole;
			}
			set
			{
				if ((this._AdminRole != value))
				{
					this.OnAdminRoleChanging(value);
					this.SendPropertyChanging();
					this._AdminRole = value;
					this.SendPropertyChanged("AdminRole");
					this.OnAdminRoleChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
