#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoreBVN
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="BVN_IW")]
	public partial class BVNDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertTb_BvnIncident(Tb_BvnIncident instance);
    partial void UpdateTb_BvnIncident(Tb_BvnIncident instance);
    partial void DeleteTb_BvnIncident(Tb_BvnIncident instance);
    #endregion
		
		public BVNDataContext() : 
				base(global::CoreBVN.Properties.Settings.Default.BVN_IWConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public BVNDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BVNDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BVNDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BVNDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Tb_BvnIncident> Tb_BvnIncidents
		{
			get
			{
				return this.GetTable<Tb_BvnIncident>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Tb_BvnIncidents")]
	public partial class Tb_BvnIncident : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _AppID;
		
		private string _DocumentID;
		
		private string _Action;
		
		private string _Status;
		
		private string _StaffName;
		
		private string _StaffNumber;
		
		private string _StaffBranch;
		
		private System.Nullable<int> _StaffBranchCode;
		
		private string _StaffDept;
		
		private string _StaffDeptCode;
		
		private string _StaffUnit;
		
		private string _StaffUnitcode;
		
		private string _StaffGrade;
		
		private string _StaffTitle;
		
		private string _StaffCategory;
		
		private string _Email;
		
		private string _BVN;
		
		private string _Firstname;
		
		private string _MiddleName;
		
		private string _LastName;
		
		private string _AccountName;
		
		private string _AccountNumber;
		
		private string _AccountStatus;
		
		private string _CustomerNames;
		
		private string _Irregularity;
		
		private string _Nature_Of_The_Irregular;
		
		private string _DomicileBranch;
		
		private string _DomicileBranchCode;
		
		private System.Nullable<int> _IsAccountClose;
		
		private string _InputStage;
		
		private System.Nullable<int> _InputStageId;
		
		private System.Nullable<System.DateTime> _DateSubmitted;
		
		private string _Comment;
		
		private string _dateOfBirth;
		
		private string _AccountNameArray;
		
		private string _AccountNumberArray;
		
		private string _AccountStatusArray;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnAppIDChanging(string value);
    partial void OnAppIDChanged();
    partial void OnDocumentIDChanging(string value);
    partial void OnDocumentIDChanged();
    partial void OnActionChanging(string value);
    partial void OnActionChanged();
    partial void OnStatusChanging(string value);
    partial void OnStatusChanged();
    partial void OnStaffNameChanging(string value);
    partial void OnStaffNameChanged();
    partial void OnStaffNumberChanging(string value);
    partial void OnStaffNumberChanged();
    partial void OnStaffBranchChanging(string value);
    partial void OnStaffBranchChanged();
    partial void OnStaffBranchCodeChanging(System.Nullable<int> value);
    partial void OnStaffBranchCodeChanged();
    partial void OnStaffDeptChanging(string value);
    partial void OnStaffDeptChanged();
    partial void OnStaffDeptCodeChanging(string value);
    partial void OnStaffDeptCodeChanged();
    partial void OnStaffUnitChanging(string value);
    partial void OnStaffUnitChanged();
    partial void OnStaffUnitcodeChanging(string value);
    partial void OnStaffUnitcodeChanged();
    partial void OnStaffGradeChanging(string value);
    partial void OnStaffGradeChanged();
    partial void OnStaffTitleChanging(string value);
    partial void OnStaffTitleChanged();
    partial void OnStaffCategoryChanging(string value);
    partial void OnStaffCategoryChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnBVNChanging(string value);
    partial void OnBVNChanged();
    partial void OnFirstnameChanging(string value);
    partial void OnFirstnameChanged();
    partial void OnMiddleNameChanging(string value);
    partial void OnMiddleNameChanged();
    partial void OnLastNameChanging(string value);
    partial void OnLastNameChanged();
    partial void OnAccountNameChanging(string value);
    partial void OnAccountNameChanged();
    partial void OnAccountNumberChanging(string value);
    partial void OnAccountNumberChanged();
    partial void OnAccountStatusChanging(string value);
    partial void OnAccountStatusChanged();
    partial void OnCustomerNamesChanging(string value);
    partial void OnCustomerNamesChanged();
    partial void OnIrregularityChanging(string value);
    partial void OnIrregularityChanged();
    partial void OnNature_Of_The_IrregularChanging(string value);
    partial void OnNature_Of_The_IrregularChanged();
    partial void OnDomicileBranchChanging(string value);
    partial void OnDomicileBranchChanged();
    partial void OnDomicileBranchCodeChanging(string value);
    partial void OnDomicileBranchCodeChanged();
    partial void OnIsAccountCloseChanging(System.Nullable<int> value);
    partial void OnIsAccountCloseChanged();
    partial void OnInputStageChanging(string value);
    partial void OnInputStageChanged();
    partial void OnInputStageIdChanging(System.Nullable<int> value);
    partial void OnInputStageIdChanged();
    partial void OnDateSubmittedChanging(System.Nullable<System.DateTime> value);
    partial void OnDateSubmittedChanged();
    partial void OnCommentChanging(string value);
    partial void OnCommentChanged();
    partial void OndateOfBirthChanging(string value);
    partial void OndateOfBirthChanged();
    partial void OnAccountNameArrayChanging(string value);
    partial void OnAccountNameArrayChanged();
    partial void OnAccountNumberArrayChanging(string value);
    partial void OnAccountNumberArrayChanged();
    partial void OnAccountStatusArrayChanging(string value);
    partial void OnAccountStatusArrayChanged();
    #endregion
		
		public Tb_BvnIncident()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AppID", DbType="VarChar(150)")]
		public string AppID
		{
			get
			{
				return this._AppID;
			}
			set
			{
				if ((this._AppID != value))
				{
					this.OnAppIDChanging(value);
					this.SendPropertyChanging();
					this._AppID = value;
					this.SendPropertyChanged("AppID");
					this.OnAppIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DocumentID", DbType="VarChar(250) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string DocumentID
		{
			get
			{
				return this._DocumentID;
			}
			set
			{
				if ((this._DocumentID != value))
				{
					this.OnDocumentIDChanging(value);
					this.SendPropertyChanging();
					this._DocumentID = value;
					this.SendPropertyChanged("DocumentID");
					this.OnDocumentIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Action", DbType="VarChar(50)")]
		public string Action
		{
			get
			{
				return this._Action;
			}
			set
			{
				if ((this._Action != value))
				{
					this.OnActionChanging(value);
					this.SendPropertyChanging();
					this._Action = value;
					this.SendPropertyChanged("Action");
					this.OnActionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="VarChar(50)")]
		public string Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this.OnStatusChanging(value);
					this.SendPropertyChanging();
					this._Status = value;
					this.SendPropertyChanged("Status");
					this.OnStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StaffName", DbType="VarChar(150)")]
		public string StaffName
		{
			get
			{
				return this._StaffName;
			}
			set
			{
				if ((this._StaffName != value))
				{
					this.OnStaffNameChanging(value);
					this.SendPropertyChanging();
					this._StaffName = value;
					this.SendPropertyChanged("StaffName");
					this.OnStaffNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StaffNumber", DbType="VarChar(150)")]
		public string StaffNumber
		{
			get
			{
				return this._StaffNumber;
			}
			set
			{
				if ((this._StaffNumber != value))
				{
					this.OnStaffNumberChanging(value);
					this.SendPropertyChanging();
					this._StaffNumber = value;
					this.SendPropertyChanged("StaffNumber");
					this.OnStaffNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StaffBranch", DbType="VarChar(150)")]
		public string StaffBranch
		{
			get
			{
				return this._StaffBranch;
			}
			set
			{
				if ((this._StaffBranch != value))
				{
					this.OnStaffBranchChanging(value);
					this.SendPropertyChanging();
					this._StaffBranch = value;
					this.SendPropertyChanged("StaffBranch");
					this.OnStaffBranchChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StaffBranchCode", DbType="Int")]
		public System.Nullable<int> StaffBranchCode
		{
			get
			{
				return this._StaffBranchCode;
			}
			set
			{
				if ((this._StaffBranchCode != value))
				{
					this.OnStaffBranchCodeChanging(value);
					this.SendPropertyChanging();
					this._StaffBranchCode = value;
					this.SendPropertyChanged("StaffBranchCode");
					this.OnStaffBranchCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StaffDept", DbType="VarChar(150)")]
		public string StaffDept
		{
			get
			{
				return this._StaffDept;
			}
			set
			{
				if ((this._StaffDept != value))
				{
					this.OnStaffDeptChanging(value);
					this.SendPropertyChanging();
					this._StaffDept = value;
					this.SendPropertyChanged("StaffDept");
					this.OnStaffDeptChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StaffDeptCode", DbType="VarChar(150)")]
		public string StaffDeptCode
		{
			get
			{
				return this._StaffDeptCode;
			}
			set
			{
				if ((this._StaffDeptCode != value))
				{
					this.OnStaffDeptCodeChanging(value);
					this.SendPropertyChanging();
					this._StaffDeptCode = value;
					this.SendPropertyChanged("StaffDeptCode");
					this.OnStaffDeptCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StaffUnit", DbType="VarChar(150)")]
		public string StaffUnit
		{
			get
			{
				return this._StaffUnit;
			}
			set
			{
				if ((this._StaffUnit != value))
				{
					this.OnStaffUnitChanging(value);
					this.SendPropertyChanging();
					this._StaffUnit = value;
					this.SendPropertyChanged("StaffUnit");
					this.OnStaffUnitChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StaffUnitcode", DbType="VarChar(150)")]
		public string StaffUnitcode
		{
			get
			{
				return this._StaffUnitcode;
			}
			set
			{
				if ((this._StaffUnitcode != value))
				{
					this.OnStaffUnitcodeChanging(value);
					this.SendPropertyChanging();
					this._StaffUnitcode = value;
					this.SendPropertyChanged("StaffUnitcode");
					this.OnStaffUnitcodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StaffGrade", DbType="VarChar(100)")]
		public string StaffGrade
		{
			get
			{
				return this._StaffGrade;
			}
			set
			{
				if ((this._StaffGrade != value))
				{
					this.OnStaffGradeChanging(value);
					this.SendPropertyChanging();
					this._StaffGrade = value;
					this.SendPropertyChanged("StaffGrade");
					this.OnStaffGradeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StaffTitle", DbType="VarChar(150)")]
		public string StaffTitle
		{
			get
			{
				return this._StaffTitle;
			}
			set
			{
				if ((this._StaffTitle != value))
				{
					this.OnStaffTitleChanging(value);
					this.SendPropertyChanging();
					this._StaffTitle = value;
					this.SendPropertyChanged("StaffTitle");
					this.OnStaffTitleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StaffCategory", DbType="VarChar(100)")]
		public string StaffCategory
		{
			get
			{
				return this._StaffCategory;
			}
			set
			{
				if ((this._StaffCategory != value))
				{
					this.OnStaffCategoryChanging(value);
					this.SendPropertyChanging();
					this._StaffCategory = value;
					this.SendPropertyChanged("StaffCategory");
					this.OnStaffCategoryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(150)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BVN", DbType="VarChar(50)")]
		public string BVN
		{
			get
			{
				return this._BVN;
			}
			set
			{
				if ((this._BVN != value))
				{
					this.OnBVNChanging(value);
					this.SendPropertyChanging();
					this._BVN = value;
					this.SendPropertyChanged("BVN");
					this.OnBVNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Firstname", DbType="VarChar(150)")]
		public string Firstname
		{
			get
			{
				return this._Firstname;
			}
			set
			{
				if ((this._Firstname != value))
				{
					this.OnFirstnameChanging(value);
					this.SendPropertyChanging();
					this._Firstname = value;
					this.SendPropertyChanged("Firstname");
					this.OnFirstnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MiddleName", DbType="VarChar(150)")]
		public string MiddleName
		{
			get
			{
				return this._MiddleName;
			}
			set
			{
				if ((this._MiddleName != value))
				{
					this.OnMiddleNameChanging(value);
					this.SendPropertyChanging();
					this._MiddleName = value;
					this.SendPropertyChanged("MiddleName");
					this.OnMiddleNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastName", DbType="VarChar(150)")]
		public string LastName
		{
			get
			{
				return this._LastName;
			}
			set
			{
				if ((this._LastName != value))
				{
					this.OnLastNameChanging(value);
					this.SendPropertyChanging();
					this._LastName = value;
					this.SendPropertyChanged("LastName");
					this.OnLastNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AccountName", DbType="VarChar(250)")]
		public string AccountName
		{
			get
			{
				return this._AccountName;
			}
			set
			{
				if ((this._AccountName != value))
				{
					this.OnAccountNameChanging(value);
					this.SendPropertyChanging();
					this._AccountName = value;
					this.SendPropertyChanged("AccountName");
					this.OnAccountNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AccountNumber", DbType="VarChar(50)")]
		public string AccountNumber
		{
			get
			{
				return this._AccountNumber;
			}
			set
			{
				if ((this._AccountNumber != value))
				{
					this.OnAccountNumberChanging(value);
					this.SendPropertyChanging();
					this._AccountNumber = value;
					this.SendPropertyChanged("AccountNumber");
					this.OnAccountNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AccountStatus", DbType="VarChar(50)")]
		public string AccountStatus
		{
			get
			{
				return this._AccountStatus;
			}
			set
			{
				if ((this._AccountStatus != value))
				{
					this.OnAccountStatusChanging(value);
					this.SendPropertyChanging();
					this._AccountStatus = value;
					this.SendPropertyChanged("AccountStatus");
					this.OnAccountStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CustomerNames", DbType="VarChar(250)")]
		public string CustomerNames
		{
			get
			{
				return this._CustomerNames;
			}
			set
			{
				if ((this._CustomerNames != value))
				{
					this.OnCustomerNamesChanging(value);
					this.SendPropertyChanging();
					this._CustomerNames = value;
					this.SendPropertyChanged("CustomerNames");
					this.OnCustomerNamesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Irregularity", DbType="VarChar(500)")]
		public string Irregularity
		{
			get
			{
				return this._Irregularity;
			}
			set
			{
				if ((this._Irregularity != value))
				{
					this.OnIrregularityChanging(value);
					this.SendPropertyChanging();
					this._Irregularity = value;
					this.SendPropertyChanged("Irregularity");
					this.OnIrregularityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nature_Of_The_Irregular", DbType="VarChar(5000)")]
		public string Nature_Of_The_Irregular
		{
			get
			{
				return this._Nature_Of_The_Irregular;
			}
			set
			{
				if ((this._Nature_Of_The_Irregular != value))
				{
					this.OnNature_Of_The_IrregularChanging(value);
					this.SendPropertyChanging();
					this._Nature_Of_The_Irregular = value;
					this.SendPropertyChanged("Nature_Of_The_Irregular");
					this.OnNature_Of_The_IrregularChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DomicileBranch", DbType="VarChar(150)")]
		public string DomicileBranch
		{
			get
			{
				return this._DomicileBranch;
			}
			set
			{
				if ((this._DomicileBranch != value))
				{
					this.OnDomicileBranchChanging(value);
					this.SendPropertyChanging();
					this._DomicileBranch = value;
					this.SendPropertyChanged("DomicileBranch");
					this.OnDomicileBranchChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DomicileBranchCode", DbType="VarChar(50)")]
		public string DomicileBranchCode
		{
			get
			{
				return this._DomicileBranchCode;
			}
			set
			{
				if ((this._DomicileBranchCode != value))
				{
					this.OnDomicileBranchCodeChanging(value);
					this.SendPropertyChanging();
					this._DomicileBranchCode = value;
					this.SendPropertyChanged("DomicileBranchCode");
					this.OnDomicileBranchCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsAccountClose", DbType="Int")]
		public System.Nullable<int> IsAccountClose
		{
			get
			{
				return this._IsAccountClose;
			}
			set
			{
				if ((this._IsAccountClose != value))
				{
					this.OnIsAccountCloseChanging(value);
					this.SendPropertyChanging();
					this._IsAccountClose = value;
					this.SendPropertyChanged("IsAccountClose");
					this.OnIsAccountCloseChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InputStage", DbType="VarChar(150)")]
		public string InputStage
		{
			get
			{
				return this._InputStage;
			}
			set
			{
				if ((this._InputStage != value))
				{
					this.OnInputStageChanging(value);
					this.SendPropertyChanging();
					this._InputStage = value;
					this.SendPropertyChanged("InputStage");
					this.OnInputStageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InputStageId", DbType="Int")]
		public System.Nullable<int> InputStageId
		{
			get
			{
				return this._InputStageId;
			}
			set
			{
				if ((this._InputStageId != value))
				{
					this.OnInputStageIdChanging(value);
					this.SendPropertyChanging();
					this._InputStageId = value;
					this.SendPropertyChanged("InputStageId");
					this.OnInputStageIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateSubmitted", DbType="DateTime")]
		public System.Nullable<System.DateTime> DateSubmitted
		{
			get
			{
				return this._DateSubmitted;
			}
			set
			{
				if ((this._DateSubmitted != value))
				{
					this.OnDateSubmittedChanging(value);
					this.SendPropertyChanging();
					this._DateSubmitted = value;
					this.SendPropertyChanged("DateSubmitted");
					this.OnDateSubmittedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Comment", DbType="VarChar(500)")]
		public string Comment
		{
			get
			{
				return this._Comment;
			}
			set
			{
				if ((this._Comment != value))
				{
					this.OnCommentChanging(value);
					this.SendPropertyChanging();
					this._Comment = value;
					this.SendPropertyChanged("Comment");
					this.OnCommentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dateOfBirth", DbType="VarChar(100)")]
		public string dateOfBirth
		{
			get
			{
				return this._dateOfBirth;
			}
			set
			{
				if ((this._dateOfBirth != value))
				{
					this.OndateOfBirthChanging(value);
					this.SendPropertyChanging();
					this._dateOfBirth = value;
					this.SendPropertyChanged("dateOfBirth");
					this.OndateOfBirthChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AccountNameArray", DbType="VarChar(1500)")]
		public string AccountNameArray
		{
			get
			{
				return this._AccountNameArray;
			}
			set
			{
				if ((this._AccountNameArray != value))
				{
					this.OnAccountNameArrayChanging(value);
					this.SendPropertyChanging();
					this._AccountNameArray = value;
					this.SendPropertyChanged("AccountNameArray");
					this.OnAccountNameArrayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AccountNumberArray", DbType="VarChar(1500)")]
		public string AccountNumberArray
		{
			get
			{
				return this._AccountNumberArray;
			}
			set
			{
				if ((this._AccountNumberArray != value))
				{
					this.OnAccountNumberArrayChanging(value);
					this.SendPropertyChanging();
					this._AccountNumberArray = value;
					this.SendPropertyChanged("AccountNumberArray");
					this.OnAccountNumberArrayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AccountStatusArray", DbType="VarChar(1500)")]
		public string AccountStatusArray
		{
			get
			{
				return this._AccountStatusArray;
			}
			set
			{
				if ((this._AccountStatusArray != value))
				{
					this.OnAccountStatusArrayChanging(value);
					this.SendPropertyChanging();
					this._AccountStatusArray = value;
					this.SendPropertyChanged("AccountStatusArray");
					this.OnAccountStatusArrayChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
